name: cabueta
on:
  workflow_dispatch:

jobs:
  somejobhere:
    special:
        uses: vtex/cabueta/.github/workflows/cabueta.yml@main
        with:
          dast-check: false
          target-url: "http://gbrls.space"
          upload-logs: true
          upload-url: "http://gbrls.space/logs"
          output-path: "./local-reports"
